# 11

create a one-dimensional array of all two-digit numbers and print this array.

Tip: use `np.arange()` function.

In [2]:
import numpy as np

In [7]:
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


# 12

Create array shown in image from class (too lazy to copy paste lol)

In [31]:
array = np.arange(10, 100)
matrix = array.reshape(9, 10)
print(matrix)

### alternatives
print('\n\n')
print(np.arange(10, 100).reshape(-1, 10))

print('\n\n')
print(np.arange(10, 100).reshape(9, 10))

print('\n\n')
print(np.arange(10, 100).reshape(9, -1))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]



[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]



[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]



[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39

# 13

create a 6x6 two-dimensional array - identity matrix with int data type.

In [3]:
print(np.eye(6, dtype=int))

### solution from class
# print(np.eye(N=6, dtype='int'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


# 14

Set the sandom seed to 10.  Then create a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution.

__Tip__: use `np.random.rand()`

In [7]:
print(np.random.rand(5, 6))

[[0.98328321 0.34004209 0.69292051 0.57429592 0.17417595 0.00998334]
 [0.64311279 0.04132937 0.35817376 0.7240784  0.6200185  0.87976481]
 [0.73333737 0.29008908 0.3787414  0.15328916 0.84659731 0.41624904]
 [0.9229453  0.6420948  0.90783951 0.0645798  0.40611542 0.85145377]
 [0.7463075  0.34205137 0.24822892 0.12271919 0.64008889 0.27796194]]
