# 21

generate a two dimensional array with integers from 0 to 11.

In [2]:
import numpy as np

In [12]:
# own solution
print(np.arange(0, 12).reshape(3, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
