# 21

generate a two dimensional array with integers from 0 to 11.

In [1]:
import numpy as np

In [14]:
# own solution
# print(np.arange(0, 12).reshape(3, -1))

# class alternative
A = np.arange(12).reshape(-1, 4)
np.save('array.npy', A)

B = np.load('array.npy')
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 23

convert a two-dimensional array into a list

__tip__: use `np.array.tolist()`

In [5]:
# A = np.array([[0, 1, 2, 3],
#               [4, 5, 6, 7],
#               [8, 9, 10, 11]])

A = np.arange(12, dtype='int').reshape(-1, 4)
print(A)
print()
print(A.tolist())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


# 24

invert A from problem 23

In [6]:
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


# 25

transform a 4x4 array of `1.`s into a version that has a frame of `0`s per class inputs.

__tip__: use `pad()`

In [15]:
A = np.ones(shape=(4, 4))
print(np.pad(A, pad_width=1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 26

convert array of 0's into same array (dimensions & ints)

In [65]:
A = np.zeros(shape=(6, 6), dtype='int')
A[::2, ::2] = 10
A[1::2, ::2] = 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


# 27 

combine two arrays into one using `np.append()`

In [6]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])

print(np.append(A, B, axis=0))

[ 0  1  2  3  4  5  6  7  8  9 10 11  4  3  7  2  0  5  2  6]
