In [1]:
import numpy as np

# 31

sort given array by row (ascending) and by column (ascending).

In [4]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

print(np.sort(A))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


# 32

extract all elements from provided array with a value greater than 8.

In [8]:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

print(A[A>8])

[ 9.99  9.99 14.99]


# 33

replace any character greater than 10 from a given array.

In [ ]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

print(np.where(A>10, A, 10.0))