In [2]:
import numpy as np

# 31

expand array shown in class by 1 dimension

In [7]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])

print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]


# 32

create a three-dimensional array called _image_  with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type `np.uint8`. Set random seed to 42. 

In [23]:
np.random.seed(42)

a = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(a)

[[[102 179  92]
  [ 14 106  71]
  [188  20 102]
  ...
  [ 70 216  44]
  [131  35  69]
  [251 158  18]]

 [[188 107 181]
  [166  90 201]
  [ 89  18  38]
  ...
  [141 222  54]
  [175 209   6]
  [ 73   6 160]]

 [[150  84 146]
  [111 124 146]
  [ 35  28 187]
  ...
  [ 36   3 219]
  [107 125  19]
  [187 151  49]]

 ...

 [[  6  46 221]
  [155 208  26]
  [209  83 185]
  ...
  [254   0 202]
  [ 80 149 205]
  [107  22 209]]

 [[146  26  17]
  [181 144 182]
  [ 89 157 225]
  ...
  [199 207 235]
  [ 98 246  44]
  [ 58 137 147]]

 [[ 34 178 138]
  [213  74 201]
  [183  77  16]
  ...
  [ 31 143 231]
  [240 251  40]
  [201   8  84]]]
