In [2]:
import numpy as np

# 41

expand array shown in class by 1 dimension

In [7]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])

print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]


# 42

create a three-dimensional array called _image_  with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type `np.uint8`. Set random seed to 42. 

In [3]:
np.random.seed(42)

a = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(a)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


# 43 

extend the given array by one timension (add a new dimension at the beginning) and assign to _image\_extended_ variable. 

Expected shape is (1, 200, 300, 3)

__tip__: use `np.expand_dims()`