In [2]:
import numpy as np

# 41

expand array shown in class by 1 dimension

In [7]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])

print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]


# 42

create a three-dimensional array called _image_  with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type `np.uint8`. Set random seed to 42. 

In [3]:
np.random.seed(42)

a = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(a)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


# 43 

extend the given array by one timension (add a new dimension at the beginning) and assign to _image\_extended_ variable. 

Expected shape is (1, 200, 300, 3)

__tip__: use `np.expand_dims()`

In [7]:
a = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(np.expand_dims(a, axis=0))

[[[[ 29  70  66]
   [ 41 246 189]
   [106 238   7]
   ...
   [165 109 184]
   [236  21 167]
   [249  13 186]]

  [[246 123  13]
   [157  67  98]
   [243 149 170]
   ...
   [141  67   7]
   [ 68 121 213]
   [ 14  85 183]]

  [[243 100 183]
   [126  29 134]
   [ 29 228 127]
   ...
   [195  99   3]
   [ 19 206 213]
   [ 45  13 158]]

  ...

  [[  0 144 109]
   [ 80  23  35]
   [ 65 111  45]
   ...
   [220 204  85]
   [ 47 254  25]
   [177 252 124]]

  [[249 240  44]
   [ 77  81  38]
   [ 70 169 235]
   ...
   [ 61 120  73]
   [223  97 144]
   [160 137  82]]

  [[247 206  15]
   [202  30 250]
   [171 148  72]
   ...
   [185 186   7]
   [  0  47 248]
   [211 161  61]]]]


# 44

Two randomly generated arrays are given, expand each of them by adding one dimension at the beginning and then combine them into one called _images_.

Expected shape of _images_ is (2, 200, 300, 3)

In [8]:
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

expanded_image1 = np.expand_dims(image1, axis=0)
expanded_image2 = np.expand_dims(image2, axis=0)

images = np.concatenate((expanded_image1, expanded_image2), axis=0)
print(images)

[[[[ 71 134  84]
   [129  53  53]
   [ 82  81  70]
   ...
   [208 113 224]
   [114  66  41]
   [ 12 118 245]]

  [[107 149  39]
   [ 69  60  42]
   [224 207  61]
   ...
   [ 32  69 206]
   [194  42   9]
   [189 131 176]]

  [[182 155 217]
   [173 177  24]
   [154  14  95]
   ...
   [ 88 252 230]
   [ 64  85 235]
   [184 184 117]]

  ...

  [[147 139 216]
   [ 78 168 200]
   [247  56 242]
   ...
   [105 105  12]
   [ 38 173 121]
   [ 45  84   7]]

  [[ 46 110 133]
   [ 11  56 158]
   [  5   8   6]
   ...
   [168  47  87]
   [136 162 176]
   [255 144  13]]

  [[127 161 252]
   [ 54 111  40]
   [114  36  25]
   ...
   [149  40 131]
   [205 243 180]
   [143  73 112]]]


 [[[ 40 248 162]
   [129 248  75]
   [ 62 142  88]
   ...
   [197  89  18]
   [189 115 123]
   [157  67 192]]

  [[ 45 185  37]
   [248 145  16]
   [160 140  28]
   ...
   [127 232  62]
   [229 255  82]
   [219 234 239]]

  [[ 94 188 226]
   [120   2 251]
   [ 18 118  86]
   ...
   [ 82 134 126]
   [242 154 111]
   [176 131

# 45

for a given array of shape (1, 2, 3), remove the unnecessary first dimension and extract (2, 3).

__tip__: use `np.squeeze()`.

In [16]:
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])

print(np.squeeze(A, axis=0))

[[1 2 3]
 [6 3 2]]
