In [2]:
import numpy as np

# 51

concatenate two given arrays.  __tip__: use `np.concatenate()`

In [5]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

print(np.concatenate((A, B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


# 52

two arrays are given, concatenate them in the expected format shown in class.

In [7]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

print(np.concatenate((data, target), axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


# 53

three one-dimensional arrays are provided, transform each into a colum and concatenate them into one array in expected format per class.

__tip__: use `np.column_stack()`

In [9]:
a = np.array([1.6, 0.9, 2.2])
b = np.array([0.4, 1.3, 3.2])
c = np.array([1.4, 0.3, 1.2])

print(np.column_stack((a, b, c)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


# 54

a two-dimensional array is given. the task is to split this array into three parts:  (i) the first two columns, (ii) the next four columns, (iii) the last to columns. 

__tip__: use `np.split()`

In [28]:
np.random.seed(42)

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


# 55

calculate the total number of non-zero elements in a given array.

In [31]:
np.random.seed(42)

A = np.random.randint(low=0, high=2, size=(10, 6))
print(np.count_nonzero(A))

31


# 56

change the specified precision to 4 in a given array.

In [45]:
np.random.seed(42)
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


# 57

in the given array, set precision to 8 and also _option_ to suppress mathematical notation

In [6]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(precision=8, suppress=True)
print(A)

[0.0000012  0.00000017]


# 58

on the given array, remove the third column.

In [16]:
np.random.seed(42)

A = np.random.randn(8, 4)
print(np.delete(A, [2], axis=1))

[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]


# 59

for a given one-dimensional array v (_vector_), calculate the norm

In [17]:
v = np.array([3, 4, -2])
print(v)

[ 3  4 -2]
