In [1]:
import numpy as np

# 51

concatenate two given arrays.  __tip__: use `np.concatenate()`

In [2]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

print(A)
print(B)

[[3 4 5]
 [8 3 1]]
[[0 5 2]
 [4 2 1]]
