In [2]:
import numpy as np

# 51

concatenate two given arrays.  __tip__: use `np.concatenate()`

In [5]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

print(np.concatenate((A, B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


# 52

two arrays are given, concatenate them in the expected format shown in class.

In [7]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

print(np.concatenate((data, target), axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


# 53

three one-dimensional arrays are provided, transform each into a colum and concatenate them into one array in expected format per class.

__tip__: use `np.column_stack()`

In [9]:
a = np.array([1.6, 0.9, 2.2])
b = np.array([0.4, 1.3, 3.2])
c = np.array([1.4, 0.3, 1.2])

print(np.column_stack((a, b, c)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


# 54

a two-dimensional array is given. the task is to split this array into three parts:  (i) the first two columns, (ii) the next four columns, (iii) the last to columns. 

__tip__: use `np.split()`