In [3]:
import numpy as np

# 51

concatenate two given arrays.  __tip__: use `np.concatenate()`

In [5]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

print(np.concatenate((A, B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


# 52

two arrays are given, concatenate them in the expected format shown in class.

In [7]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

print(np.concatenate((data, target), axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


# 53

three one-dimensional arrays are provided, transform each into a colum and concatenate them into one array in expected format per class.

__tip__: use `np.column_stack()`

In [9]:
a = np.array([1.6, 0.9, 2.2])
b = np.array([0.4, 1.3, 3.2])
c = np.array([1.4, 0.3, 1.2])

print(np.column_stack((a, b, c)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


# 54

a two-dimensional array is given. the task is to split this array into three parts:  (i) the first two columns, (ii) the next four columns, (iii) the last to columns. 

__tip__: use `np.split()`

In [28]:
np.random.seed(42)

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


# 55

calculate the total number of non-zero elements in a given array.

In [31]:
np.random.seed(42)

A = np.random.randint(low=0, high=2, size=(10, 6))
print(np.count_nonzero(A))

31


# 56

change the specified precision to 4 in a given array.

In [ ]:
np.random.seed(42)

A = np.random.randn(10, 4)
print(A)