In [2]:
import numpy as np

# 51

concatenate two given arrays.  __tip__: use `np.concatenate()`

In [5]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

print(np.concatenate((A, B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


# 52

two arrays are given, concatenate them in the expected format shown in class.

In [6]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

print(np.concatenate((data, target), axis=1))

TypeError: concatenate() got an unexpected keyword argument 'axix'