In [1]:
import numpy as np
print(np.__version__)

1.19.1


# 61

for the given arrays, calculate the arithmetic means (elementwise)

In [4]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# print((A + B) / 2)
print(np.divide(np.add(A, B), 2))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


# 62

two arrays are given, multiply these arrays element-wise

In [5]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

print(A)
print(B)

[[3 4 9 2]
 [5 3 2 5]]
[[4 3 2 5]
 [6 3 1 6]]
