In [2]:
import numpy as np
print(np.__version__)

1.19.1


# 61

for the given arrays, calculate the arithmetic means (elementwise)

In [4]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# print((A + B) / 2)
print(np.divide(np.add(A, B), 2))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


# 62

two arrays are given, multiply these arrays element-wise

In [8]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# print(np.multiply(A, B))
print(A * B)

[[12 12 18 10]
 [30  9  2 30]]


# 63

got a given array, calculate the square root of each element.

In [5]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


# 64

check the pythagorean formula for sines and cosines on the A array and the compare them with the B array.

__tip__: use `np.allclose()`

In [6]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

print(A)
print(B)

[0.         0.08267349 0.16534698 0.24802047 0.33069396 0.41336745
 0.49604095 0.57871444 0.66138793 0.74406142 0.82673491 0.9094084
 0.99208189 1.07475538 1.15742887 1.24010236 1.32277585 1.40544935
 1.48812284 1.57079633]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
