In [1]:
import numpy as np
print(np.__version__)

1.19.1


# 61

for the given arrays, calculate the arithmetic means (elementwise)

In [4]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# print((A + B) / 2)
print(np.divide(np.add(A, B), 2))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


# 62

two arrays are given, multiply these arrays element-wise

In [8]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

# print(np.multiply(A, B))
print(A * B)

[[12 12 18 10]
 [30  9  2 30]]


# 63

got a given array, calculate the square root of each element.

In [5]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


# 64

check the pythagorean formula for sines and cosines on the A array and the compare them with the B array.

__tip__: use `np.allclose()`

In [16]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

# print(np.sin(A) ** 2 + np.cos(A) ** 2)
print(np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B))


True


# 65

perform a matrix multiplication A x B for the given arrays.

In [4]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])

# print(np.dot(A, B))
print(A.dot(B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


# 66

on a given array (a square matrix), calculate the determinant

__tip__: use `np.linalg.det()`

In [5]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])

print(np.linalg.det(A))

51.999999999999986


# 67

for a given matrix;  calculate eigenvalues and their corresponding eigenvectors of this matrix.

__tip__: use `np.linalg.eig()`

In [2]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

print(A)

[[  5   8  16]
 [  4   1   8]
 [ -4   4 -11]]
