In [1]:
import numpy as np
print(np.__version__)

1.19.1


# 71

for a given array, randomly shuffle the rows starting with the second row.

__tip__: use `np.random.shuffle()`

In [26]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['005' '1.49']
 ['004' '2.49']
 ['003' '7.99']
 ['001' '14.99']]


# 72

return a list of indexes that sorts a given array in ascending order

__tip__: use `np.argsort()`

In [28]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
print(np.argsort(A))

[5 2 1 0 4 3]


# 73

for a given array, round the values to three decimal places

In [3]:
np.random.seed(42)
A = np.random.randn(10, 8)
print(np.round(A, decimals=3))

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]


# 74

calculate the root of the given polynomial

In [4]:
W = np.array([4, 5, 1])
print(np.roots(W))

[-1.   -0.25]


# 75

calculate the roots of the given polynomial

In [10]:
Q = np.array([2, 4, -5, 1])
R = np.array([2, 0, -5, 1])
print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


# 76

for the given polynomials, perform the indicated operations

In [ ]:
### expected output

[2 8 0 2]
[-2 0 10 0]
[ 8 26  2 -17  0  1]
[ 4 12 -5 3]